name: Verify Templating

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  apply-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply Templates
        run: ./apply-templates.sh
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          [ -z "$status" ]
- isim: Önbellek
  kullanımlar: action/cache@v3.2.6
  ile:
    # Önbelleğe alınacak ve geri yüklenecek dosyaların, dizinlerin ve joker karakter kalıplarının bir listesi
    yol:
    # Önbelleği geri yüklemek ve kaydetmek için açık bir anahtar
    anahtar:
    # Anahtar için önbellek isabeti oluşmadıysa, eski önbelleği geri yüklemek için kullanılacak sıralı bir anahtar listesi. Not "cache-hit" bu durumda false değerini döndürür.
    geri yükleme anahtarları: # isteğe bağlı
    # Yükleme sırasında büyük dosyaları bayt olarak bölmek için kullanılan öbek boyutu
    yükleme yığını boyutu: # isteğe bağlı
    # Etkinleştirildiğinde isteğe bağlı bir boole, Windows çalıştırıcılarının diğer platformlarda sırasıyla geri yüklenebilen veya kaydedilebilen önbellekleri kaydetmesine veya geri yüklemesine olanak tanır
    enableCrossOsArchive: # isteğe bağlı, varsayılan değer yanlış
    # Önbellek girişi bulunamazsa iş akışı başarısız olur
    önbellekte arıza: # isteğe bağlı, varsayılan değer yanlış
